sudo: required

services:
  - docker

before_install:
  - docker build -t hwibell/react-test -f client/Dockerfile.dev client

script:
  - docker run -e CI=true hwibell/react-test npm test

after_success:
  - docker build -t hwibell/multi-client  client
  - docker build -t hwibell/multi-nginx nginx
  - docker build -t hwibell/multi-server server
  - docker build -t hwibell/multi-worker worker
  # Log in to docker CLI
  - docker login --username "${DOCKER_USERNAME}" --password "${DOCKER_TOKEN}"
  # Push images to Docker Hub
  - docker push hwibell/multi-client
  - docker push hwibell/multi-nginx
  - docker push hwibell/multi-server
  - docker push hwibell/multi-worker
